### ISSUE TITLE
Discussion about this library

### ISSUE THREAD

**Issue by teras** [smyrgeorge/sqlx4k#2]
This is more of a discussion board for this library, since no discussion is enabled. Please feel free to move this.

I understand that this is your project, but let me have a few comments about it. I had an overview and what was my first impression was the API. I am worried that there is one more API, given there's already a similar low level API: JDBC.

I mean, of course we don't want/need 100% implementation. Maybe only 10% is enough. But, this 10% to be virtually the same. Like for example, how transactions are implemented. The API should be Kotlin/Java/JDBC like and not Rust like. That's what I believe.

**Comment by smyrgeorge** [comment]
To be honest I don't understand exactly your comment.

First of all there is no kotlin native driver (written in pure kotlin) outhere, the ecosystem is in a very young stage. 

Secondly this project does not target jvm at all, so the comparison with jdbc is not accurate. Although this project (also sqlx) they were build with jooq in mind but of course I didn't copy it.

Also, I understand that maybe I could come up with a more kotlinish api. That's probably true, in that case I would be happy to also view your opinion on that.

After all it's a two month project written exclusively by me. I think it's not a fair comparison with projects that have several contributors.

Thanks a lot 🙂

**Comment by smyrgeorge** [comment]
Also, I enabled the discussions.

**Comment by teras** [comment]
Do you mind converting this "issue" to a discussion, so we can better talk there ?
